# Generated by Django 4.1.2 on 2022-10-28 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_room_categories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="categories",
            new_name="category",
        ),
    ]
