# Generated by Django 4.1.2 on 2022-10-28 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0002_experience_categories_alter_perk_detail_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="categories",
            new_name="category",
        ),
    ]
